export const DEFAULT_TEMPLATE_FIELDS = [
  {
    type: "attendance_days",
    label: "An welchen Tagen bist du dabei?",
    required: true,
    options: [] as string[],
    settings: {},
    description: null,
  },
  {
    type: "multi_select",
    label: "Auf-/Abbau",
    required: false,
    options: ["Aufbau/Packen", "Abbau/Aufräumen"],
    settings: {},
    description: null,
  },
  {
    type: "checkbox",
    label: "Kann einen Anhänger zur Verfügung stellen",
    required: false,
    options: [] as string[],
    settings: {},
    description: null,
  },
  {
    type: "checkbox",
    label: "Reise mit eigenem PKW an",
    required: false,
    options: [] as string[],
    settings: {},
    description: null,
  },
  {
    type: "checkbox",
    label: "Kann einen Anhänger mit dem PKW ziehen",
    required: false,
    options: [] as string[],
    settings: { conditional_on: "Reise mit eigenem PKW an" },
    description: "Wird nur angezeigt, wenn PKW-Anreise ausgewählt ist",
  },
  {
    type: "checkbox",
    label: "Bereit einzukaufen",
    required: false,
    options: [] as string[],
    settings: {},
    description: null,
  },
  {
    type: "checkbox",
    label: "Helfe im Orgateam Küche mit",
    required: false,
    options: [] as string[],
    settings: {},
    description: null,
  },
  {
    type: "select",
    label: "Ernährungspräferenz",
    required: false,
    options: ["Keine Einschränkung", "Vegetarisch", "Vegan"],
    settings: {},
    description: null,
  },
  {
    type: "textarea",
    label: "Allergien / Unverträglichkeiten",
    required: false,
    options: [] as string[],
    settings: { placeholder: "Bitte angeben, falls vorhanden" },
    description: null,
  },
  {
    type: "tent",
    label: "Zelt-Details",
    required: false,
    options: [] as string[],
    settings: {},
    description: "Angaben zu deinem Zelt für die Lagerplanung",
  },
  {
    type: "checkbox",
    label: "Ausrüstung vollständig",
    required: false,
    options: [] as string[],
    settings: {},
    description: "Hast du alles, was du brauchst?",
  },
  {
    type: "textarea",
    label: "Anmerkungen",
    required: false,
    options: [] as string[],
    settings: { placeholder: "Sonstige Hinweise..." },
    description: null,
  },
];
